from preprocessing.data_cleaning import ArabicCleaner
from preprocessing.data_processor import ArabicDiacritizationProcessor
from preprocessing.diacritization_dataset import DiacritizationDataset

from utils import collate_fn

from fastapi import FastAPI